"""Core package - exceptions, logging, security"""
from .exceptions import (
    QuizBotException,
    DatabaseException,
    EntityNotFoundError,
    DuplicateEntityError,
    QuizException,
    QuizNotFoundError,
    QuizAlreadyActiveError,
    NoQuestionsError,
    UserException,
    UserBlockedError,
    UserNotSubscribedError,
    PaymentException,
    InsufficientStarsError,
    SubscriptionExpiredError,
    RateLimitException,
    ValidationException,
    InvalidInputError,
)
from .logging import (
    setup_logging,
    get_logger,
    LoggerMixin,
    bind_user_context,
    bind_chat_context,
    clear_context,
    audit_logger,
)
from .security import (
    InputValidator,
    RateLimiter,
    rate_limiter,
    rate_limit,
    generate_secure_token,
    generate_referral_code,
    verify_referral_code,
    admin_required,
    super_admin_required,
)

__all__ = [
    # Exceptions
    "QuizBotException",
    "DatabaseException",
    "EntityNotFoundError",
    "DuplicateEntityError",
    "QuizException",
    "QuizNotFoundError",
    "QuizAlreadyActiveError",
    "NoQuestionsError",
    "UserException",
    "UserBlockedError",
    "UserNotSubscribedError",
    "PaymentException",
    "InsufficientStarsError",
    "SubscriptionExpiredError",
    "RateLimitException",
    "ValidationException",
    "InvalidInputError",
    # Logging
    "setup_logging",
    "get_logger",
    "LoggerMixin",
    "bind_user_context",
    "bind_chat_context",
    "clear_context",
    "audit_logger",
    # Security
    "InputValidator",
    "RateLimiter",
    "rate_limiter",
    "rate_limit",
    "generate_secure_token",
    "generate_referral_code",
    "verify_referral_code",
    "admin_required",
    "super_admin_required",
]
